#!/srv/openode/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'gunicorn==0.17.2','console_scripts','gunicorn_django'
__requires__ = 'gunicorn==0.17.2'
import sys
from pkg_resources import load_entry_point


sys.stdout = sys.stderr

import os

sys.path.append('/srv/openode/app')
sys.path.append('/srv/openode/site')

os.environ['DJANGO_SETTINGS_MODULE'] = 'openode.settings'


if __name__ == '__main__':
    sys.exit(
        load_entry_point('gunicorn==0.17.2', 'console_scripts', 'gunicorn_django')()
    )